export const ROCK_PAPER_SCISSORS = 'ROCK_PAPER_SCISSORS';

export const OUTCOME_WIN = 'win';
export const OUTCOME_DRAW = 'draw';
export const OUTCOME_LOSE = 'lose';

export const DISPLAY_START_SCREEN = 'DISPLAY_START_SCREEN';
export const COMPUTER_OR_HUMAN_PLAYER = 'COMPUTER_OR_HUMAN_PLAYER';
export const SELECT_SIGNAL_OPTION = 'SELECT_SIGNAL_OPTION';
export const REVEAL_SELECTED_SIGNAL_OPTIONS = 'REVEAL_SELECTED_SIGNAL_OPTIONS';
export const START_GAME = 'START_GAME';
export const RESTART_GAME = 'RESTART_GAME';
export const DECIDE_WINNER = 'DECIDE_WINNER';
export const INCREMENT_PLAYER_SCORE = 'INCREMENT_PLAYER_SCORE';